# Generated by Django 3.2.15 on 2023-02-11 10:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_authorproflie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorProflie',
            new_name='AuthorProfile',
        ),
    ]
